## Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.


In [1]:
import numpy as np


In [8]:
##create an array using Numpy
#create a 1D array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [11]:
arr=np.array([1,2,3,4,5])
arr.reshape(1,5)#i row and 5 column

array([[1, 2, 3, 4, 5]])

In [14]:
#creating 2D array
arr2=np.array([[1,2,3],[5,8,9]])
print(arr2)
print(arr2.shape)
arr2.reshape(3,2)# 3 row and 2 column

[[1 2 3]
 [5 8 9]]
(2, 3)


array([[1, 2],
       [3, 5],
       [8, 9]])

In [17]:
#creating array using inbuilt function
np.arange(0,10,2)



array([0, 2, 4, 6, 8])

In [18]:

np.arange(0,10,2).reshape(5,1)



array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((3,4))# 3*4 matrix with one value

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#creating identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [27]:
##Numpy vectorized opertaion
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
#element wise addititon
print("addition:",arr1+arr2)
#element wise subtraction
print("subtraction:",arr1-arr2)
#element wise multiplication
print("multiplication:",arr1*arr2)
#element wise division
print("division:",arr1/arr2)


addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [32]:
#universal function
arr1=np.array([1,2,3,4,5])
#square root
print(np.sqrt(arr1))

##exponential
print(np.exp(arr1))

##sine
print(np.sin(arr1))

##natural log
print(np.log(arr1))





[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [40]:
#array slicing and indexing
arr=np.array([[1,2,3,9],[4,5,6,3],[7,8,9,15]])
print(arr)


[[ 1  2  3  9]
 [ 4  5  6  3]
 [ 7  8  9 15]]


In [48]:
print(arr[0][0])
print(arr[1:])
print(arr[0:2])
print(arr[0:2,2:])

1
[[ 4  5  6  3]
 [ 7  8  9 15]]
[[1 2 3 9]
 [4 5 6 3]]
[[3 9]
 [6 3]]


In [42]:
arr[1:,2:]


array([[ 6,  3],
       [ 9, 15]])

In [51]:
#modify array
arr[0][0]=36
print(arr)

[[36  2  3  9]
 [ 4  5  6  3]
 [ 7  8  9 15]]


In [54]:
#ststistical concepts--Normalization
#to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])
#calculating mean and stdeviation

mean=np.mean(data)
st_deviation=np.std(data)
#normalize the data
normalize_data=(data-mean)/st_deviation
print(f"Normalized data :{normalize_data}")


Normalized data :[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [63]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [69]:
#logical opertaion
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[data>5]
data[(data>5) & (data<8)]


array([6, 7])