In [1]:
#importing numpy
import numpy as np

Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
arr=np.random.randint(1,21,size=(5,5))
print(arr)
#replacing 1 to third column
print()
arr[:,1]=1
print(arr)

[[10  8  8  7 16]
 [16  2  4  5 20]
 [14 18 11  1 16]
 [ 9 12 20  9  8]
 [ 7  1 12 10  6]]

[[10  1  8  7 16]
 [16  1  4  5 20]
 [14  1 11  1 16]
 [ 9  1 20  9  8]
 [ 7  1 12 10  6]]


Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [3]:
arr=(np.arange(1,17)).reshape(4,4)
print("original array")
print(arr)
np.fill_diagonal(arr,0)

print("MOdified array")
print(arr)

original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
MOdified array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns

In [4]:
arr=(np.arange(1,37)).reshape(6,6)
print("original array \n")
print(arr)
#3rd to 5th rows and 2nd to 4th columns
sub_array=arr[2:5,1:4]
print(sub_array)


original array 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr=np.random.randint(1,100,size=(5,5))
print("original array")
print(arr)

#accessing the border iteam
border_element=np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_element)


original array
[[ 9 82 76 95 56]
 [37 16 35 77 27]
 [65 79 29  2  4]
 [54 79 69 19 53]
 [49 10  5 64 84]]
[ 9 82 76 95 56 49 10  5 64 84 37 65 54 27  4 53]


Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1=np.random.randint(1,50,size=(5,5))
arr2=np.random.randint(1,50,size=(5,5))
print(arr1)
print()
print(arr2)
#addition
print("Addition")
print(arr1+arr2)
#Subtraction
print("Subtraction")
print(arr1-arr2)

#multipiaction
print("multipiaction")
print(arr1*arr2)
#Division
print("Division")
print(arr1/arr2)



[[16 10 43 27 31]
 [ 3 38  8 47 49]
 [10 40 46 19 27]
 [14  4 12 26 28]
 [25  7 44 18  1]]

[[36  8 29 47  3]
 [13 31 29 37  5]
 [19 34 41 37 36]
 [40 42  3  7  1]
 [ 2 44 14 47 24]]
Addition
[[52 18 72 74 34]
 [16 69 37 84 54]
 [29 74 87 56 63]
 [54 46 15 33 29]
 [27 51 58 65 25]]
Subtraction
[[-20   2  14 -20  28]
 [-10   7 -21  10  44]
 [ -9   6   5 -18  -9]
 [-26 -38   9  19  27]
 [ 23 -37  30 -29 -23]]
multipiaction
[[ 576   80 1247 1269   93]
 [  39 1178  232 1739  245]
 [ 190 1360 1886  703  972]
 [ 560  168   36  182   28]
 [  50  308  616  846   24]]
Division
[[ 0.44444444  1.25        1.48275862  0.57446809 10.33333333]
 [ 0.23076923  1.22580645  0.27586207  1.27027027  9.8       ]
 [ 0.52631579  1.17647059  1.12195122  0.51351351  0.75      ]
 [ 0.35        0.0952381   4.          3.71428571 28.        ]
 [12.5         0.15909091  3.14285714  0.38297872  0.04166667]]


Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [7]:
arr=(np.arange(1,17)).reshape(4,4)
print("original array")
print(arr)

original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
row_wise_sum=np.sum(arr,axis=1)
column_wise_sum=np.sum(arr,axis=0)
print("row wise sum")
print(row_wise_sum)
print("column wise sum")
print(column_wise_sum)


row wise sum
[10 26 42 58]
column wise sum
[28 32 36 40]


Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [9]:
arr=np.random.randint(1,50,size=(5,5))
print("original array")
print(arr)

print("mean")
print(np.mean(arr))
print("median")
print(np.median(arr))
print("standard deviation")
print(np.std(arr))
print("vaiance")
print(np.var(arr))


original array
[[25 34 11 16 20]
 [47  3 16  1 18]
 [ 1  2 35 13 19]
 [42 16 24 10 19]
 [31 43 32 10 37]]
mean
21.0
median
19.0
standard deviation
13.344661854089821
vaiance
178.08


 Broadcasting

Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [38]:
arr1=np.random.randint(1,50,size=(3,3))
print(arr1)

arr2=np.random.randint(1,50,size=(3,))
print()
print(arr2)
sum_broadacast=arr1+arr2

print(sum_broadacast)

[[48 16 28]
 [27 28 44]
 [39 25 29]]

[ 2 27 10]
[[50 43 38]
 [29 55 54]
 [41 52 39]]


Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [36]:
arr1=np.random.randint(1,50,size=(4,4))
print(arr1)

arr2=np.random.randint(1,50,size=(4,))
print()
print(arr2)
print()
sub_broadacast=arr1-arr2

print(sub_broadacast)

[[49 28 40 49]
 [ 5  3 31 12]
 [ 7 26 47 15]
 [32 22 33 26]]

[25 29 13  7]

[[ 24  -1  27  42]
 [-20 -26  18   5]
 [-18  -3  34   8]
 [  7  -7  20  19]]


Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [56]:
arr1=np.random.randint(1,10,size=(3,3))
print("Original array")
print(arr1)
print("determinant")
determinant=np.linalg.det(arr1)
print(determinant)
print("inverse")
print(np.linalg.inv(arr1))
print("eigen value")
eg_value=np.linalg.eigvals(arr1)
print(eg_value)
eigen_value,eigen_vector=np.linalg.eig(arr1)
print(eigen_value)
print("eigen vector")
print(eigen_vector)

Original array
[[2 3 2]
 [4 5 8]
 [6 1 7]]
determinant
61.99999999999995
inverse
[[ 0.43548387 -0.30645161  0.22580645]
 [ 0.32258065  0.03225806 -0.12903226]
 [-0.41935484  0.25806452 -0.03225806]]
eigen value
[12.20387856+0.j          0.89806072+2.06732654j  0.89806072-2.06732654j]
[12.20387856+0.j          0.89806072+2.06732654j  0.89806072-2.06732654j]
eigen vector
[[-0.33313707+0.j          0.11889488-0.56688297j  0.11889488+0.56688297j]
 [-0.77743197+0.j          0.58739085+0.j          0.58739085-0.j        ]
 [-0.53349716+0.j         -0.36062764+0.43523257j -0.36062764-0.43523257j]]


Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [64]:
arr1=np.random.randint(1,10,size=(2,3))
print(arr1)
print()

arr2=np.random.randint(1,10,size=(3,2))
print(arr2)
result=np.dot(arr1,arr2)
print("matrix multiplication of arr1 and arr2")
print(result)

[[5 8 8]
 [8 9 9]]

[[2 9]
 [4 3]
 [9 1]]
matrix multiplication of arr1 and arr2
[[114  77]
 [133 108]]


Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [71]:
arr=(np.arange(1,10)).reshape(3,3)
print(arr)
arr1=arr.reshape((1,9))
print(arr1)
arr2=arr.reshape((9,1))
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [76]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[16  4 13 20  3]
 [19 17  6  4 11]
 [13  8 19  2 18]
 [14  7 18  1 19]
 [13 17  7  5 20]]
Flattened array:
[16  4 13 20  3 19 17  6  4 11 13  8 19  2 18 14  7 18  1 19 13 17  7  5
 20]
Reshaped array:
[[16  4 13 20  3]
 [19 17  6  4 11]
 [13  8 19  2 18]
 [14  7 18  1 19]
 [13 17  7  5 20]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [78]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[11  2  3  9 15]
 [17  9 18 14  3]
 [15  7  3  8 13]
 [ 4  4  2 12 14]
 [ 5 13 18 20 16]]
Corner elements:
[11 15  5 16]


Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [79]:

# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[16 13 18 14]
 [ 1 12 20 20]
 [15  5 12 10]
 [ 3 11  9  7]]
Modified array:
[[10 10 10 10]
 [ 1 10 10 10]
 [10  5 10 10]
 [ 3 10  9  7]]


Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [80]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [81]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


 Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [82]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[10 20  4  4]
 [ 3 16 13 11]
 [ 1  9  3 13]
 [16 11  9 14]]
Masked array:
[[10 -- 4 4]
 [3 -- -- --]
 [1 9 3 --]
 [-- -- 9 --]]
Sum of unmasked elements: 43


Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [83]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[20  7 15]
 [12  7 13]
 [ 2  6 12]]
Masked array:
[[-- 7 15]
 [12 -- 13]
 [2 6 --]]
Modified masked array:
[[ 9  7 15]
 [12  9 13]
 [ 2  6  9]]
